language: node_js
node_js:
- stable
deploy:
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: public
  provider: pages
  skip-cleanup: true
  on:
    branch: master
env:
  global:
    secure: bondE+ZjH9uF3pGLSVcBbZjCxgwH6T2UbdD3zDbxKAW1jQrHSkr1qRYXRJXSC6O6ZUnYnPoURT8m44MAXMg877YAG6ggoKhDbsexx5hRdt3qe0SZWz8rj8n1eUAB9rO3mjRul7X6gAg5S3yA6F4Ye7P46YU8WBqdy4aiR0NmpfA=
